/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class CkPdf {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CkPdf(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CkPdf obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        chilkatJNI.delete_CkPdf(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CkPdf() {
    this(chilkatJNI.new_CkPdf(), true);
  }

  public void LastErrorXml(CkString str) {
    chilkatJNI.CkPdf_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorHtml(CkString str) {
    chilkatJNI.CkPdf_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorText(CkString str) {
    chilkatJNI.CkPdf_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void get_DebugLogFilePath(CkString str) {
    chilkatJNI.CkPdf_get_DebugLogFilePath(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String debugLogFilePath() {
    return chilkatJNI.CkPdf_debugLogFilePath(swigCPtr, this);
  }

  public void put_DebugLogFilePath(String newVal) {
    chilkatJNI.CkPdf_put_DebugLogFilePath(swigCPtr, this, newVal);
  }

  public void get_LastErrorHtml(CkString str) {
    chilkatJNI.CkPdf_get_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorHtml() {
    return chilkatJNI.CkPdf_lastErrorHtml(swigCPtr, this);
  }

  public void get_LastErrorText(CkString str) {
    chilkatJNI.CkPdf_get_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorText() {
    return chilkatJNI.CkPdf_lastErrorText(swigCPtr, this);
  }

  public void get_LastErrorXml(CkString str) {
    chilkatJNI.CkPdf_get_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorXml() {
    return chilkatJNI.CkPdf_lastErrorXml(swigCPtr, this);
  }

  public boolean get_LastMethodSuccess() {
    return chilkatJNI.CkPdf_get_LastMethodSuccess(swigCPtr, this);
  }

  public void put_LastMethodSuccess(boolean newVal) {
    chilkatJNI.CkPdf_put_LastMethodSuccess(swigCPtr, this, newVal);
  }

  public void get_LoadOwnerPassword(CkString str) {
    chilkatJNI.CkPdf_get_LoadOwnerPassword(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String loadOwnerPassword() {
    return chilkatJNI.CkPdf_loadOwnerPassword(swigCPtr, this);
  }

  public void put_LoadOwnerPassword(String newVal) {
    chilkatJNI.CkPdf_put_LoadOwnerPassword(swigCPtr, this, newVal);
  }

  public void get_LoadUserPassword(CkString str) {
    chilkatJNI.CkPdf_get_LoadUserPassword(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String loadUserPassword() {
    return chilkatJNI.CkPdf_loadUserPassword(swigCPtr, this);
  }

  public void put_LoadUserPassword(String newVal) {
    chilkatJNI.CkPdf_put_LoadUserPassword(swigCPtr, this, newVal);
  }

  public int get_NumSignatures() {
    return chilkatJNI.CkPdf_get_NumSignatures(swigCPtr, this);
  }

  public void get_UncommonOptions(CkString str) {
    chilkatJNI.CkPdf_get_UncommonOptions(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String uncommonOptions() {
    return chilkatJNI.CkPdf_uncommonOptions(swigCPtr, this);
  }

  public void put_UncommonOptions(String newVal) {
    chilkatJNI.CkPdf_put_UncommonOptions(swigCPtr, this, newVal);
  }

  public boolean get_VerboseLogging() {
    return chilkatJNI.CkPdf_get_VerboseLogging(swigCPtr, this);
  }

  public void put_VerboseLogging(boolean newVal) {
    chilkatJNI.CkPdf_put_VerboseLogging(swigCPtr, this, newVal);
  }

  public void get_Version(CkString str) {
    chilkatJNI.CkPdf_get_Version(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String version() {
    return chilkatJNI.CkPdf_version(swigCPtr, this);
  }

  public boolean LoadBd(CkBinData pdfData) {
    return chilkatJNI.CkPdf_LoadBd(swigCPtr, this, CkBinData.getCPtr(pdfData), pdfData);
  }

  public boolean LoadFile(String filePath) {
    return chilkatJNI.CkPdf_LoadFile(swigCPtr, this, filePath);
  }

  public boolean SaveLastError(String path) {
    return chilkatJNI.CkPdf_SaveLastError(swigCPtr, this, path);
  }

  public boolean VerifySignature(int index, CkJsonObject sigInfo) {
    return chilkatJNI.CkPdf_VerifySignature(swigCPtr, this, index, CkJsonObject.getCPtr(sigInfo), sigInfo);
  }

}
